version: "3"
services:
  db:
    image: mongo:4
    container_name: mongodb
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bq
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27018:27017"
    restart: always
    networks:
      - private
  node:
    image: node:14 # https://hub.docker.com/_/node/
    container_name: node
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mongodb://bq:secret@db:27017/bq?authSource=admin
      JWT_SECRET: "${JWT_SECRET}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 80:8080
    command: bash -c 'rm -rf node_modules package-lock.json && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
